#! /bin/bash

programname=$0

function usage {
    echo "usage: $programname searchtext [directory]"
    exit 1
}

[ -z $1 ] && usage
if [ $FORMAT != "jar" ] || [ $FORMAT != "war" ] || [ $FORMAT != "ear" ]; then
	usage
fi


DIR=$2
if [ -z $DIR ]; then
	DIR=$(pwd)
fi

FORMAT=$3

if [ -z $FORMAT ]; then
	FORMAT=jar
fi

find "$DIR" -type f -name "*.$FORMAT" | while read JAR; do
	echo "Searching JAR: $JAR"
	echo --- $(zipgrep $1 "$JAR")
done
