SELECT STRING_VALUE, TIME_STAMP
FROM loc_state_journal 
WHERE STATUS_TYPCODE = 'RTL_LOC_STATE'
AND RTL_LOC_ID = '800' 
AND ORGANIZATION_ID = '1'
AND TIME_STAMP = (SELECT MAX(TIME_STAMP)
	FROM loc_state_journal);