-- sale line items
SELECT li.TRANS_SEQ, li.RTRANS_LINEITM_SEQ, li.RTRANS_LINEITM_TYPCODE, sli.ITEM_ID, sli.QUANTITY, sli.UNIT_PRICE, sli.PRICE_PROPERTY_CODE, sli.GROSS_AMT, sli.RETURN_FLAG, sli.RETURN_TYPCODE, sli.ORIGINAL_TRANS_SEQ, sli.INITIAL_QUANTITY 
FROM trl_rtrans_lineitm li
JOIN TRL_RTRANS rt
ON rt.ORGANIZATION_ID = li.ORGANIZATION_ID
AND rt.RTL_LOC_ID = li.RTL_LOC_ID
AND rt.BUSINESS_DATE = li.BUSINESS_DATE
AND rt.TRANS_SEQ = li.TRANS_SEQ
JOIN trl_sale_lineitm sli
ON sli.ORGANIZATION_ID = li.ORGANIZATION_ID
AND sli.RTL_LOC_ID = li.RTL_LOC_ID
AND sli.BUSINESS_DATE = li.BUSINESS_DATE
AND sli.TRANS_SEQ = li.TRANS_SEQ
AND sli.RTRANS_LINEITM_SEQ = li.RTRANS_LINEITM_SEQ
AND li.RTRANS_LINEITM_TYPCODE = 'ITEM'
AND rt.TRANS_SEQ = '778';


-- tender line items
SELECT li.TRANS_SEQ, li.RTRANS_LINEITM_SEQ, li.RTRANS_LINEITM_TYPCODE, tndli.AMT, tndli.TNDR_ID, tndli.TNDR_STATCODE
FROM trl_rtrans_lineitm li
JOIN TRL_RTRANS rt
ON rt.ORGANIZATION_ID = li.ORGANIZATION_ID
AND rt.RTL_LOC_ID = li.RTL_LOC_ID
AND rt.BUSINESS_DATE = li.BUSINESS_DATE
AND rt.TRANS_SEQ = li.TRANS_SEQ
JOIN ttr_tndr_lineitm tndli
ON tndli.ORGANIZATION_ID = li.ORGANIZATION_ID
AND tndli.RTL_LOC_ID = li.RTL_LOC_ID
AND tndli.BUSINESS_DATE = li.BUSINESS_DATE
AND tndli.TRANS_SEQ = li.TRANS_SEQ
AND tndli.RTRANS_LINEITM_SEQ = li.RTRANS_LINEITM_SEQ
AND li.RTRANS_LINEITM_TYPCODE = 'TENDER'
AND rt.TRANS_SEQ = '778';


-- tax line items
SELECT li.TRANS_SEQ, li.RTRANS_LINEITM_SEQ, li.RTRANS_LINEITM_TYPCODE, taxli.TAX_RULE_SEQ_NBR, taxli.TAXABLE_AMT, taxli.TAX_AMT, taxli.TAX_PERCENTAGE, taxli.AUTHORITY_ID, taxli.AUTHORITY_TYPE_CODE
FROM trl_rtrans_lineitm li
JOIN TRL_RTRANS rt
ON rt.ORGANIZATION_ID = li.ORGANIZATION_ID
AND rt.RTL_LOC_ID = li.RTL_LOC_ID
AND rt.BUSINESS_DATE = li.BUSINESS_DATE
AND rt.TRANS_SEQ = li.TRANS_SEQ
JOIN trl_tax_lineitm taxli
ON taxli.ORGANIZATION_ID = li.ORGANIZATION_ID
AND taxli.RTL_LOC_ID = li.RTL_LOC_ID
AND taxli.BUSINESS_DATE = li.BUSINESS_DATE
AND taxli.TRANS_SEQ = li.TRANS_SEQ
AND taxli.RTRANS_LINEITM_SEQ = li.RTRANS_LINEITM_SEQ
AND li.RTRANS_LINEITM_TYPCODE = 'TAX'
AND rt.TRANS_SEQ = '778';
